<?php
/**
 * Policy pages and cookie-policy generator.
 *
 * @package PCM
 */

namespace PCM;

defined( 'ABSPATH' ) || exit;

/**
 * Links the banner to policy pages and generates an editable cookie-policy
 * draft from the configured services. Generated text is a starting point
 * that MUST be reviewed by the site's legal/privacy team.
 */
class Policy_Manager {

	/**
	 * Registers hooks.
	 */
	public function register() {}

	/**
	 * Generates a cookie policy draft from the current configuration.
	 *
	 * @return string HTML.
	 */
	public function generate_cookie_policy() {
		$sections = array();

		$services = array();
		if ( pcm_get_setting( 'ga4.enabled' ) && pcm_get_setting( 'ga4.measurement_id' ) ) {
			$services[] = array(
				'name'    => __( 'Google Analytics 4', 'privacy-consent-manager' ),
				'purpose' => __( 'Measures website usage and visitor behaviour in aggregate.', 'privacy-consent-manager' ),
				'vendor'  => 'Google LLC',
				'category' => pcm_get_setting( 'ga4.category', 'analytics' ),
			);
		}
		if ( pcm_get_setting( 'clarity.enabled' ) && pcm_get_setting( 'clarity.project_id' ) ) {
			$services[] = array(
				'name'    => __( 'Microsoft Clarity', 'privacy-consent-manager' ),
				'purpose' => __( 'Session replays and heatmaps to understand how the site is used.', 'privacy-consent-manager' ),
				'vendor'  => 'Microsoft Corporation',
				'category' => pcm_get_setting( 'clarity.category', 'analytics' ),
			);
		}
		if ( pcm_get_setting( 'cloudflare.enabled' ) && pcm_get_setting( 'cloudflare.token' ) ) {
			$services[] = array(
				'name'    => __( 'Cloudflare Web Analytics', 'privacy-consent-manager' ),
				'purpose' => __( 'Privacy-first, cookieless website analytics.', 'privacy-consent-manager' ),
				'vendor'  => 'Cloudflare, Inc.',
				'category' => pcm_get_setting( 'cloudflare.category', 'analytics' ),
			);
		}
		if ( pcm_get_setting( 'gtm.enabled' ) && pcm_get_setting( 'gtm.container_id' ) ) {
			$services[] = array(
				'name'    => __( 'Google Tag Manager', 'privacy-consent-manager' ),
				'purpose' => __( 'Manages and loads additional tags and scripts.', 'privacy-consent-manager' ),
				'vendor'  => 'Google LLC',
				'category' => pcm_get_setting( 'gtm.category', 'marketing' ),
			);
		}
		foreach ( (array) pcm_get_setting( 'custom_scripts', array() ) as $script ) {
			if ( empty( $script['enabled'] ) ) {
				continue;
			}
			$services[] = array(
				'name'     => $script['name'],
				'purpose'  => __( 'Custom script configured by the site administrator.', 'privacy-consent-manager' ),
				'vendor'   => '',
				'category' => $script['category'],
			);
		}

		$categories = pcm_get_setting( 'categories', Settings::default_categories() );

		$sections[] = '<h2>' . esc_html__( 'Cookie Policy', 'privacy-consent-manager' ) . '</h2>';
		$sections[] = '<p><em>' . esc_html__( 'DRAFT — generated by Privacy & Consent Manager. This text is a technical starting point only. Have it reviewed and completed by your legal or privacy team before publishing.', 'privacy-consent-manager' ) . '</em></p>';
		$sections[] = '<p>' . esc_html__( 'This website uses cookies and similar technologies. You can change your consent at any time using the "Privacy Settings" link.', 'privacy-consent-manager' ) . '</p>';

		$sections[] = '<h3>' . esc_html__( 'Consent categories', 'privacy-consent-manager' ) . '</h3><ul>';
		foreach ( $categories as $category ) {
			$sections[] = '<li><strong>' . esc_html( $category['label'] ) . '</strong> — ' . esc_html( $category['description'] ) . '</li>';
		}
		$sections[] = '</ul>';

		if ( $services ) {
			$sections[] = '<h3>' . esc_html__( 'Services in use', 'privacy-consent-manager' ) . '</h3>';
			$sections[] = '<table><thead><tr><th>' . esc_html__( 'Service', 'privacy-consent-manager' ) . '</th><th>' . esc_html__( 'Vendor', 'privacy-consent-manager' ) . '</th><th>' . esc_html__( 'Purpose', 'privacy-consent-manager' ) . '</th><th>' . esc_html__( 'Category', 'privacy-consent-manager' ) . '</th></tr></thead><tbody>';
			foreach ( $services as $service ) {
				$sections[] = '<tr><td>' . esc_html( $service['name'] ) . '</td><td>' . esc_html( $service['vendor'] ) . '</td><td>' . esc_html( $service['purpose'] ) . '</td><td>' . esc_html( $service['category'] ) . '</td></tr>';
			}
			$sections[] = '</tbody></table>';
		}

		/**
		 * Filters the generated cookie policy draft.
		 *
		 * @param string $html     Generated HTML.
		 * @param array  $services Detected services.
		 */
		return apply_filters( 'pcm_generated_cookie_policy', implode( "\n", $sections ), $services );
	}
}
